[build]
command = "echo \"window.env = { FIREBASE_API_KEY: '${FIREBASE_API_KEY}', FIREBASE_AUTH_DOMAIN: '${FIREBASE_AUTH_DOMAIN}', FIREBASE_PROJECT_ID: '${FIREBASE_PROJECT_ID}', FIREBASE_STORAGE_BUCKET: '${FIREBASE_STORAGE_BUCKET}', FIREBASE_MESSAGING_SENDER_ID: '${FIREBASE_MESSAGING_SENDER_ID}', FIREBASE_APP_ID: '${FIREBASE_APP_ID}' };\" > functions/env.js"
publish = "."

[[headers]]
for = "/functions/env.js"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"
